--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MakerbakerYT/AdvertisingKick
build-by-default: true
depends:
- scoreboard
branches:
- main
projects:
  AdvertisingKick:
    path: ""
...
